arguments:
    parameters:
        - name: application-name-dev
          value: pipeline20-app1
        - name: application-name-stag
          value: pipeline20-app2
        - name: revision
          value: main
        - name: argocd-server-address
          value: argocd-server.argocd.svc.cluster.local
        - name: argocd-credentials-secret
          value: argocd-user
