metadata:
    generateName: pipeline7
    labels:
        clusterName: cluster2
    namespace: argo
spec:
    arguments:
        parameters:
            - name: example
              value: example
            - name: revision
              value: main
            - name: argocd-server-address
              value: argocd-server.argocd.svc.cluster.local
            - name: argocd-credentials-secret
              value: argocd-user
    entrypoint: starter
    templates:
        - name: starter
          steps:
            - - arguments:
                    parameters:
                        - name: application-name
                          value: '{{workflow.parameters.application-name-dev}}'
                        - name: revision
                          value: '{{workflow.parameters.revision}}'
                        - name: argocd-server-address
                          value: '{{workflow.parameters.argocd-server-address}}'
                name: deploy-to-dev-successes1
                templateRef:
                    name: argocd-step
                    template: argocd-sync-and-wait
