arguments:
    parameters:
        - name: application-name
          value: pipeline40-app1
        - name: application-name-2
          value: pipeline40-app2
        - name: revision
          value: HEAD
        - name: argocd-server-address
          value: demoargocd.greenops.io
        - name: argocd-credentials-secret
          value: argocd-credentials-secret
